algorithm: openmatch
save_dir: ./saved_models/openset_cv
save_name: openmatch_cifar100_200_0
resume: True
load_path: ./saved_models/openset_cv/openmatch_cifar100_200_0/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 512
num_train_iter: 524288
num_eval_iter: 1024
num_labels: 200
batch_size: 64
eval_batch_size: 2561
p_cutoff: 0
ulb_loss_ratio: 1.0
lambda_em: 0.1
lambda_socr: 1.0
start_fix: 5
uratio: 2
fix_uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar100_openset
train_sampler: RandomSampler
num_classes: 50
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
