#探索半监督开放集方法的上限,做一个80分类的任务，取前16个超类，每类50个标记数据，未标记数据中不含ood
algorithm: fixmatch
save_dir: ./saved_models/openset_cv
save_name: fixmatch_cifar100_4000_0
resume: False
load_path: ./saved_models/openset_cv/fixmatch_cifar100_4000_0/latest_model.pth
overwrite: True
use_tensorboard: True
#epoch: 1
#num_train_iter: 1
#num_eval_iter: 1
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024

num_labels: 4000

batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar100_openset
train_sampler: RandomSampler
num_classes: 80
num_workers: 1
seed: 0
world_size: 1
rank: 0

multiprocessing_distributed: True

dist_url: tcp://127.0.0.1:10005
dist_backend: nccl
gpu: None
exp_group: cifar100_pure