algorithm: fixmatch
save_dir: ./saved_models/openset_cv
save_name: fixmatch_in30_p1_1
resume: False
load_path: ./saved_models/openset_cv/fixmatch_in30_p1_1/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 1
num_eval_iter: 1
#epoch: 100
#num_train_iter: 102400
#num_eval_iter: 1024
num_labels: 260
labeled_percent: p1
batch_size: 1
#batch_size: 32
eval_batch_size: 1
#eval_batch_size: 128
hard_label: True
T: 0.5
p_cutoff: 0.95
q_cutoff: 0.5
ulb_loss_ratio: 1.0
uratio: 1
da_len: 32
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet18
net_from_name: False
data_dir: ./data
dataset: imagenet30
train_sampler: RandomSampler
num_classes: 20
num_workers: 1
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10055
dist_backend: nccl
gpu: None
