algorithm: fixmatch
save_dir: ./saved_models/openset_cv
save_name: fixmatch_cifar10_300_0_noisy_unlabeled
resume: False
load_path: ./saved_models/openset_cv/fixmatch_cifar10_300_0_noisy_unlabeled/latest_model.pth
overwrite: True
use_tensorboard: True
#epoch: 1
#num_train_iter: 1
#num_eval_iter: 1
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024

num_labels: 300

batch_size: 64
eval_batch_size: 256
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar10_openset
train_sampler: RandomSampler
num_classes: 6
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None

exp_group: cifar10_easy
pure_unlabeled: False
